### ISSUE TITLE
Support WalletConnect

### ISSUE THREAD

**Issue by nesbocaj** [rtoken-project/rtoken-contracts#42]
ACs:

- Integrate WalletConnect as an alternative to MetaMask
- Test
- Create a pull request at https://github.com/WalletConnect/walletconnect-website to have rDAI added to the list of supported dApps for some free advertisement.

**Comment by nesbocaj** [comment]
Wrong repository, sorry

**Comment by hellwolf** [comment]
yep, it is dup with https://github.com/rtoken-project/rdai-app/issues/9
