### ISSUE TITLE
[RESEARCH] Thegraph integration research

### ISSUE THREAD

**Issue by hellwolf** [rtoken-project/rtoken-contracts#5]
what can we achieve from the graph integration?

**Comment by bertux** [comment]
We have created a Telegram group for that. Ask us to be invited if you want to contribute.
We will start a first version soon and try to demonstrate it at the next community call.

**Comment by bertux** [comment]
Base repository created at https://github.com/hackgraph/rdai and I will push the version scaffolded by TheGraph before modifying anything.
